fix: This does not work with Mitogen, set strategy to linear
```
ModuleNotFoundError: 'lib' is present in the Mitogen importer blacklist,
therefore this context will not attempt to request it from the master, as the
request will always be refused.
```